### ISSUE TITLE
Add more recipes

### ISSUE THREAD

**Issue by tenzinpalden** [tenzinpalden/Let-Em-Cook#7]

**Comment by snoopy0328** [comment]
Replaced and added 40 recipes, also fixed the format of the information of the recipes.
<img width="323" alt="{BC949BEC-5BB7-4AB9-B025-10D54DD0CCAF}" src="https://github.com/user-attachments/assets/9adc52b1-6aeb-4bcd-afa9-7386d47922bc">

**Comment by snoopy0328** [comment]
Updated the filters for the updated recipes
